# Generated by Django 3.1.1 on 2020-12-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoiceEmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='City',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='Country',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='Phone_Number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='State',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
