# Generated by Django 3.1.1 on 2020-12-06 04:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VoiceEmail', '0002_auto_20201206_0956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='extendeduser',
            new_name='User_Details',
        ),
    ]
