# Generated by Django 3.1.1 on 2020-12-06 04:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VoiceEmail', '0003_auto_20201206_1015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Details',
            new_name='User_Detail',
        ),
    ]
