# Generated by Django 3.1.1 on 2020-12-10 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VoiceEmail', '0006_auto_20201210_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
