# Generated by Django 3.1.1 on 2020-12-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoiceEmail', '0010_auto_20201210_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='Phone_Number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
