# Generated by Django 3.1.1 on 2020-12-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoiceEmail', '0011_auto_20201210_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='Age',
            field=models.IntegerField(null=True),
        ),
    ]
